#!/bin/bash

# Remove auto-load module line and create a backup file
sed -i.save '/sharp-drm/d' /etc/modules

# Remove configuration line and create a backup file
sed -i.save '/dtoverlay=sharp-drm/d' /boot/config.txt

# Remove device tree overlay
[ -e /boot/firmware/overlays/sharp-drm.dtbo ] && mv /boot/firmware/overlays/sharp-drm.dtbo /boot/firmware/overlays/sharp-drm_old.dtbo || true
[ -e /boot/overlays/sharp-drm.dtbo ] && mv /boot/overlays/sharp-drm.dtbo /boot/overlays/sharp-drm_old.dtbo || true
